# Credit card Fraud
Author: Krishnav Dave

### Problem Statement

Build an automation which could classify future transaction as valid or fraud

### Dataset

1.Month: transaction month

2.Date: transaction date

3.Day: transaction day

4.Time: transaction time

5.Origin_City: city where the customer is registered from

6.Destination_City: city where the transaction is generated

7.Transaction_Type: method of payment (Point of sales or internet)

8.Type: Valid transaction or raud transaction

9.Amount: transaction amount

### Code Structure

1. Import Data

2. Data Preparation

3. EDA

4. ML - Ensemble Techniques

5. Conclusion

### Load Data

In [1]:
# Standrd Library
import pandas as pd
import numpy as np

In [2]:
# Training dataset
DB = pd.read_excel("Credi_Card_Fraud.xlsx",sheet_name='DB')
DB=DB.iloc[:,1:10]
DB.head()

Month  Date  Day  Time Origin_City Destination_City Transaction_Type  \
0   Dec     3  Sun    17      Mumbai          Karachi              POS   
1   May    13  Mon     3        Bhuj         Valencia              POS   
2   May    11  Wed     3    Srinagar           Meerut              POS   
3   Feb    16  Thu    13     Chennai             Agra              POS   
4   Jul    25  Thu    22     Kolkata             Pune              POS   

     Type  Amount  
0  Normal   39972  
1  Normal  255014  
2  Normal   15476  
3  Normal  254803  
4  Normal  134982

In [3]:
DB.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 9 columns):
Month               5000 non-null object
Date                5000 non-null int64
Day                 5000 non-null object
Time                5000 non-null int64
Origin_City         5000 non-null object
Destination_City    5000 non-null object
Transaction_Type    5000 non-null object
Type                5000 non-null object
Amount              5000 non-null int64
dtypes: int64(3), object(6)
memory usage: 351.6+ KB


### Data Preparation

In [4]:
# Categorial to numeric

from sklearn.preprocessing import Imputer
from sklearn import preprocessing

le = preprocessing.LabelEncoder()

DB['Amount'] = le.fit_transform(DB['Amount'])
DB['Transaction_Type'] = le.fit_transform(DB['Transaction_Type'])
DB['Type'] = le.fit_transform(DB['Type'])
DB['Month'] = le.fit_transform(DB['Month'])
DB['Day'] = le.fit_transform(DB['Day'])

In [5]:
# Categorical to numeric : CITY [If origin city and destination city not equal then flag it 1]

DB['City']=0
for i in range(len(DB['Month'])):
    a=DB.ix[i,'Origin_City']
    b=DB.ix[i,'Destination_City']
    if a==b:
        DB.ix[i,'City']=0
    else:
        DB.ix[i,'City']=1

C:\Users\PRITHVIRAJ\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:5: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """
C:\Users\PRITHVIRAJ\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  
C:\Users\PRITHVIRAJ\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:10: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  # Remove the CWD fr

In [6]:
# Categorical to numeric : Amount  [if amount greater than its mean then assign it 1]

DB['Amount_Class']=0
mean=DB['Amount'].mean()
for i in range(len(DB['Amount'])):
    a=DB.ix[i,'Amount']
    if a>=mean:
        DB.ix[i,'Amount_Class']=1
    else:
        DB.ix[i,'Amount_Class']=0

C:\Users\PRITHVIRAJ\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  
C:\Users\PRITHVIRAJ\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:10: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  # Remove the CWD from sys.path while we load stuff.
C:\Users\PRITHVIRAJ\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:8: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.htm

In [7]:
# Categorical to mnumeric : Type

for i in range(len(DB['Type'])):
    a=DB.ix[i,'Type']
    if a==0:
        DB.ix[i,'Type']=1
    else:
        DB.ix[i,'Type']=0

C:\Users\PRITHVIRAJ\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  after removing the cwd from sys.path.
C:\Users\PRITHVIRAJ\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:8: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  
C:\Users\PRITHVIRAJ\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is

In [8]:
DB.head()

Month  Date  Day  Time Origin_City Destination_City  Transaction_Type  \
0      2     3    3    17      Mumbai          Karachi                 1   
1      8    13    1     3        Bhuj         Valencia                 1   
2      8    11    6     3    Srinagar           Meerut                 1   
3      3    16    4    13     Chennai             Agra                 1   
4      5    25    4    22     Kolkata             Pune                 1   

   Type  Amount  City  Amount_Class  
0     0     588     1             0  
1     0    3609     1             1  
2     0     220     1             0  
3     0    3604     1             1  
4     0    1897     1             0

In [9]:
DB.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 11 columns):
Month               5000 non-null int32
Date                5000 non-null int64
Day                 5000 non-null int32
Time                5000 non-null int64
Origin_City         5000 non-null object
Destination_City    5000 non-null object
Transaction_Type    5000 non-null int32
Type                5000 non-null int32
Amount              5000 non-null int64
City                5000 non-null int64
Amount_Class        5000 non-null int64
dtypes: int32(4), int64(5), object(2)
memory usage: 351.6+ KB


In [10]:
DB.describe().T

count       mean          std  min      25%     50%  \
Month             5000.0     5.4616     3.418079  0.0     2.75     5.0   
Date              5000.0    16.1524     8.905203  1.0     9.00    16.0   
Day               5000.0     3.0122     1.998412  0.0     1.00     3.0   
Time              5000.0    11.3532     7.064250  0.0     5.00    11.0   
Transaction_Type  5000.0     0.5016     0.500047  0.0     0.00     1.0   
Type              5000.0     0.2024     0.401829  0.0     0.00     0.0   
Amount            5000.0  2482.2602  1434.580598  0.0  1239.75  2485.5   
City              5000.0     0.9760     0.153064  0.0     1.00     1.0   
Amount_Class      5000.0     0.5006     0.500050  0.0     0.00     1.0   

                      75%     max  
Month                8.00    11.0  
Date                24.00    31.0  
Day                  5.00     6.0  
Time                17.00    23.0  
Transaction_Type     1.00     1.0  
Type                 0.00     1.0  
Amount            3722.25  4968.0  
City                 1.00     1.0  
Amount_Class         1.00     1.0

## EDA

In [11]:
# Target balance check: Not balanced in this case

DB['Type'].value_counts()

0    3988
1    1012
Name: Type, dtype: int64

In [12]:
# Location vs fraud

# Origin
Origin = DB['Origin_City'].dropna()
Unique_Origin = set(Origin)
print ("Unique Origin cities", len(Unique_Origin))

# Destination City
Destination = DB['Destination_City'].dropna()
Unique_Destination = set(Origin)
print ("Unique Destination cities", len(Unique_Destination))

# Group 
Group=DB.groupby(['Origin_City','Destination_City'])['Type'].sum().sort_values(ascending=False)
Group.head(10)

Unique Origin cities 23
Unique Destination cities 23


Origin_City  Destination_City
Chennai      Rajkot              6
Lucknow      Jeddah              6
Chennai      Bhuj                6
             Gurugram            5
Chandigarh   Phoenix             5
Nasik        Chennai             5
Pune         Sau Paulo           5
             Pune                5
Chennai      New york            5
Delhi        Vadodara            5
Name: Type, dtype: int32

In [13]:
# Time and date vs fraud

# Date
Date = DB['Date'].dropna()
Unique_Date = set(Date)
print ("Unique Dates", len(Unique_Date))

# Time
Time = DB['Time'].dropna()
Unique_Time = set(Time)
print ("Unique Time", len(Unique_Time))

# Time
Day = DB['Day'].dropna()
Unique_Day = set(Day)
print ("Unique Day", len(Unique_Day))

# Time
Month = DB['Month'].dropna()
Unique_Month = set(Month)
print ("Unique Month", len(Unique_Month))

Unique Dates 31
Unique Time 24
Unique Day 7
Unique Month 12


In [14]:
# Group: Date vs Type Fraud
Group=DB.groupby(['Date'])['Type'].sum().sort_values(ascending=False)
Group.head(10)

Date
28    52
26    45
7     44
2     40
27    40
14    40
15    38
11    38
1     36
24    35
Name: Type, dtype: int32

In [15]:
# Group: Time vs Type Fraud 
Group=DB.groupby(['Time'])['Type'].sum().sort_values(ascending=False)
Group.head(10)

Time
8     58
0     51
1     50
10    49
12    48
5     46
3     44
4     43
7     42
21    42
Name: Type, dtype: int32

In [16]:
# Group: Day vs Type Fraud 
Group=DB.groupby(['Day'])['Type'].sum().sort_values(ascending=False)
Group.head(10)

Day
6    155
2    153
3    147
5    145
1    144
4    135
0    133
Name: Type, dtype: int32

In [17]:
# Group: Month vs Type Fraud 
Group=DB.groupby(['Month'])['Type'].sum().sort_values(ascending=False)
Group.head(10)

Month
6     107
4      95
10     89
0      89
2      86
9      83
3      83
1      83
11     77
7      77
Name: Type, dtype: int32

In [18]:
# Group : All parameters vs fraud
Group=DB.groupby(['Month','Date','Time','Day'])['Type'].sum().sort_values(ascending=False)
Group.head(10)

Month  Date  Time  Day
8      8     8     0      2
1      15    6     2      2
7      16    2     3      2
2      29    16    1      2
9      24    12    1      2
2      10    22    1      2
10     27    8     3      2
9      14    22    3      2
6      12    11    4      2
4      11    0     1      2
Name: Type, dtype: int32

In [19]:
# Group 
Group=DB.groupby(['Date','Time','Day'])['Type'].sum().sort_values(ascending=False)
Group.head(10)

Date  Time  Day
15    0     6      3
14    22    3      3
31    19    1      3
25    5     6      3
28    5     0      2
9     3     1      2
26    0     0      2
10    22    1      2
26    0     5      2
27    21    1      2
Name: Type, dtype: int32

In [20]:
# Total FRAUD LOSSES

Amount_Fraud=0
Amount_Total=0

for i in range(len(DB['Type'])):
    Amount_Total=Amount_Total+DB.loc[i,"Amount"]
    if DB.ix[i,'Type']==1:
        Amount_Fraud=Amount_Fraud+DB.loc[i,"Amount"]

print("Total Fradulent Amount:",Amount_Fraud)
print("Total  Amount:",Amount_Total)
print("Fraud Amount %",round(100*Amount_Fraud/Amount_Total,2),'%')

Total Fradulent Amount: 2517052
Total  Amount: 12411301
Fraud Amount % 20.28 %


C:\Users\PRITHVIRAJ\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:8: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  


### Machine Learning: Ensemble tech

In [21]:
# Independent vs target variable

y = DB['Type']
X = DB[['Month','Date','Day','Time','Transaction_Type','City','Amount_Class']]

# Test Train Split

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.30, random_state=100)

In [22]:
# Normalisation
#from sklearn.preprocessing import StandardScaler
#X_train_sd = StandardScaler().fit_transform(X_train)
#X_test_sd = StandardScaler().fit_transform(X_test)

In [23]:
# Library
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics
from sklearn.metrics import accuracy_score,f1_score,recall_score,precision_score, confusion_matrix

# Model
model_DT=DecisionTreeClassifier(criterion='entropy',max_depth=4)
model_DT.fit(X_train, y_train)

# Accuracy
Accuracy_DT_Train=model_DT.score(X_train, y_train)
Accuracy_DT_Test=model_DT.score(X_test, y_test)
#print("Training Accuracy:",Accuracy_DT_Train)
#print("Test Accuracy:",Accuracy_DT_Test)

Predict_DT=model_DT.predict(X_test)
Recall_DT = recall_score(y_test,Predict_DT,average="binary", pos_label=1)

print("Confusion Matrix:\n",metrics.confusion_matrix(y_test, Predict_DT))



#Store the accuracy results for each model in a dataframe for final comparison
resultsDf = pd.DataFrame({'Method':['Decision Tree'], 'Train Accuracy': Accuracy_DT_Train, 'Test Accuracy': Accuracy_DT_Test , 'Recall': Recall_DT})
resultsDf = resultsDf[['Method', 'Train Accuracy', 'Test Accuracy', 'Recall']]
resultsDf

Confusion Matrix:
 [[1191    0]
 [ 309    0]]


Method  Train Accuracy  Test Accuracy  Recall
0  Decision Tree        0.799143          0.794     0.0

In [24]:
# Library
from sklearn.ensemble import RandomForestClassifier

# Model
model_RF = RandomForestClassifier(n_estimators =100,bootstrap=True, oob_score=True)
model_RF.fit(X_train, y_train)

# Accuracy
pred_RF = model_RF.predict(X_train)
Accuracy_RF_Train = accuracy_score(y_train, pred_RF)

pred_RF1 = model_RF.predict(X_test)
Accuracy_RF_Test = accuracy_score(y_test, pred_RF1)

#print(" Train Accuracy:",Accuracy_RF_Train)
#print(" Train Accuracy:",Accuracy_RF_Test)
print("Confusion Matrix:\n",metrics.confusion_matrix(y_test, pred_RF1))

Recall_RF = recall_score(y_test,pred_RF1,average="binary", pos_label=1)

#Store the accuracy results for each model in a dataframe for final comparison
resultsDf = pd.DataFrame({'Method':['Random Forest'], 'Train Accuracy': Accuracy_RF_Train, 'Test Accuracy': Accuracy_RF_Test , 'Recall': Recall_RF})
resultsDf = resultsDf[['Method', 'Train Accuracy', 'Test Accuracy', 'Recall']]
resultsDf



Confusion Matrix:
 [[1155   36]
 [ 303    6]]


Method  Train Accuracy  Test Accuracy    Recall
0  Random Forest        0.998857          0.774  0.019417

In [25]:
# Library
from sklearn.ensemble import AdaBoostClassifier

# Model
model_ADA_Boost = AdaBoostClassifier( n_estimators= 50, learning_rate=0.001, random_state=52)
abcl = model_ADA_Boost.fit(X_train, y_train)

# Accuracy
pred_AB =model_ADA_Boost.predict(X_train)
Accuracy_ADA_Train = accuracy_score(y_train, pred_AB)
#print("Training Accuracy:",acc_AB)

pred_AB =model_ADA_Boost.predict(X_test)
Accuracy_ADA_Test = accuracy_score(y_test, pred_AB)
# print("Training Accuracy:",acc_AB)
print("Confusion Matrix:\n",metrics.confusion_matrix(y_test, pred_AB))

Recall_Ada = recall_score(y_test,pred_AB,average="binary", pos_label=1)

#Store the accuracy results for each model in a dataframe for final comparison
resultsDf = pd.DataFrame({'Method':['ADA Boosting'], 'Train Accuracy': Accuracy_ADA_Train, 'Test Accuracy': Accuracy_ADA_Test , 'Recall': Recall_Ada})
resultsDf = resultsDf[['Method', 'Train Accuracy', 'Test Accuracy', 'Recall']]
resultsDf




Confusion Matrix:
 [[1191    0]
 [ 309    0]]


Method  Train Accuracy  Test Accuracy  Recall
0  ADA Boosting        0.799143          0.794     0.0

In [26]:
# Library
from sklearn.ensemble import GradientBoostingClassifier

# Model
model_Grad = GradientBoostingClassifier(n_estimators = 50, learning_rate = 0.001, random_state=52)
model_Grad = model_Grad.fit(X_train, y_train)

# Accuracy
pred_GB =model_Grad.predict(X_train)
Accuracy_GRAD_Train = accuracy_score(y_train, pred_GB)
#print("Training Accuracy:",acc_GB)

# Accuracy
pred_GB =model_Grad.predict(X_test)
Accuracy_GRAD_Test = accuracy_score(y_test, pred_GB)
#print("Training Accuracy:",acc_GB)
print("Confusion Matrix:\n",metrics.confusion_matrix(y_test, pred_GB))

Recall_Grad = recall_score(y_test,pred_GB,average="binary", pos_label=1)

#Store the accuracy results for each model in a dataframe for final comparison
resultsDf = pd.DataFrame({'Method':['Gradient Boosting'], 'Train Accuracy': Accuracy_GRAD_Train, 'Test Accuracy': Accuracy_GRAD_Test , 'Recall': Recall_Grad})
resultsDf = resultsDf[['Method', 'Train Accuracy', 'Test Accuracy', 'Recall']]
resultsDf

Confusion Matrix:
 [[1191    0]
 [ 309    0]]


Method  Train Accuracy  Test Accuracy  Recall
0  Gradient Boosting        0.799143          0.794     0.0

In [27]:
# Library
from sklearn.ensemble import BaggingClassifier

# Model
model_BAG = BaggingClassifier(n_estimators=20, max_samples=.8, random_state=100)
model_BAG = model_BAG.fit(X_train, y_train)

# Accuracy
pred_BG =model_BAG.predict(X_train)
Accuracy_BAG_Train = accuracy_score(y_train, pred_BG)
#print("Training Accuracy:",Accuracy_BAG_Train)

pred_BG =model_BAG.predict(X_test)
Accuracy_BAG_Test = accuracy_score(y_test, pred_BG)
#print("Training Accuracy:",Accuracy_BAG_Test)
print("Confusion Matrix:\n",metrics.confusion_matrix(y_test, pred_BG))

Recall_BAG = recall_score(y_test,pred_BG,average="binary", pos_label=1)

#Store the accuracy results for each model in a dataframe for final comparison
resultsDf = pd.DataFrame({'Method':['Bagging'], 'Train Accuracy': Accuracy_BAG_Train, 'Test Accuracy': Accuracy_BAG_Test , 'Recall': Recall_BAG})
resultsDf = resultsDf[['Method', 'Train Accuracy', 'Test Accuracy', 'Recall']]
resultsDf

Confusion Matrix:
 [[1141   50]
 [ 291   18]]


Method  Train Accuracy  Test Accuracy    Recall
0  Bagging        0.968857       0.772667  0.058252

# Choose the best working algorithm from above